// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_wtcoW5q68R21QO5C-OguDSAeve9zvk',
    appId: '1:914928616672:web:8b0ec077f3f468a1f03c85',
    messagingSenderId: '914928616672',
    projectId: 'khmerfoodrecipe',
    authDomain: 'khmerfoodrecipe.firebaseapp.com',
    storageBucket: 'khmerfoodrecipe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcvLDBOn-gUPG36eZ0tegsGEiQvOqD9Ck',
    appId: '1:914928616672:android:1db2a81aff9ac6b4f03c85',
    messagingSenderId: '914928616672',
    projectId: 'khmerfoodrecipe',
    storageBucket: 'khmerfoodrecipe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKjr0I0EgDHT6vCl5VqZk0iT_R5g1c0do',
    appId: '1:914928616672:ios:2ea97e0fac275782f03c85',
    messagingSenderId: '914928616672',
    projectId: 'khmerfoodrecipe',
    storageBucket: 'khmerfoodrecipe.firebasestorage.app',
    iosBundleId: 'com.food.khmerfoodrecipe',
  );

}